partners = [
    ['Local Historian', 'High School Student'],
    ['Astronaut', 'Science Fiction Writer'],
    ['Baker', 'Fitness Coach'],
    ['Librarian', 'Video Game Developer'],
    ['Botanical Researcher', 'Landscape Painter'],
    ['Jazz Musician', 'Classical Composer'],
    ['Robotics Engineer', 'Kindergarten Teacher'],
    ['Chef', 'Food Critic'],
    ['Mountain Guide', 'Nature Photographer'],
    ['Surgeon', 'Philosophy Professor'],
    ['Startup Founder', 'Investment Banker'],
    ['Environmental Activist', 'Industrialist'],
    ['Fashion Designer', 'Anthropologist'],
    ['Urban Planner', 'Street Artist'],
    ['Marine Biologist', 'Surfer'],
    ['Zookeeper', 'Children’s Book Author'],
    ['Professional Gamer', 'Sportscaster'],
    ['AI Ethicist', 'Futurist'],
    ['Veterinarian', 'Pet Shop Owner'],
    ['Concert Violinist', 'Rock Guitarist'],
    ['Archaeologist', 'Science Fiction Fan'],
    ['Mystery Novelist', 'Detective'],
    ['Wedding Planner', 'Divorce Lawyer'],
    ['Agriculturalist', 'Chef'],
    ['Carpenter', 'Architect'],
    ['Stand-up Comedian', 'Drama Teacher'],
    ['Nurse', 'Playwright'],
    ['Pilot', 'Travel Blogger'],
    ['Meteorologist', 'Storm Chaser'],
    ['Sommelier', 'Grape Farmer'],
    ['Magician', 'Skeptic'],
    ['Art Curator', 'Graffiti Artist'],
    ['Cybersecurity Expert', 'Hacker'],
    ['Politician', 'Political Science Student'],
    ['Geneticist', 'Ethicist'],
    ['Tattoo Artist', 'Art Historian'],
    ['Perfumer', 'Florist'],
    ['Barista', 'Coffee Bean Farmer'],
    ['Cinematographer', 'Stunt Double'],
    ['Quantum Physicist', 'Spiritual Guru'],
    ['Dentist', 'Candy Maker'],
    ['Yoga Instructor', 'Physiotherapist'],
    ['Voice Actor', 'Scriptwriter'],
    ['Organic Farmer', 'Vegan Chef'],
    ['Martial Arts Instructor', 'Ballet Dancer'],
    ['Astronomer', 'Astrologer'],
    ['Epidemiologist', 'Conspiracy Theorist'],
    ['Firefighter', 'Arson Investigator'],
    ['Speech Therapist', 'Rapper'],
    ['Neuroscientist', 'Mindfulness Coach'],
    ['Ghostwriter', 'Celebrity'],
    ['Documentary Filmmaker', 'Wildlife Conservationist']
]
