scenarios = [
    ['Walking a Dog', ['City Park', 'Beach', 'Forest Trail']],
    ['Planning a Trip to Mars', ['Space Agency HQ',
                                 'Astronomy Lab', 'Virtual Reality Simulator']],
    ['Campaigning for a Politician', [
        'Town Hall', 'City Streets', 'University Campus']],
    ['Running a Luxury Hotel', ['Tropical Island',
                                'Downtown Skyscraper', 'Historic Castle']],
    ['Doing Dishes', ['Home Kitchen', 'Restaurant Kitchen', 'Campsite']],
    ['Directing a Movie', ['Film Studio', 'Remote Desert', 'Urban Alley']],
    ['Attending a Robotics Competition', ['Tech Expo',
                                          'University Auditorium', 'Online Platform']],
    ['Writing a Fantasy Novel', ['Quiet Study',
                                 'Café in a Historic Town', 'Under a Tree in a Park']],
    ['Conducting a Scientific Experiment', ['Research Lab',
                                            'High School Science Room', 'Garage Workshop']],
    ['Playing in a Jazz Band', ['Music Club', 'Street Corner', 'Jazz Festival']],
    ['Repairing an Ancient Artifact', ['Museum Workshop',
                                       'Archaeological Site', 'University Lab']],
    ['Teaching a Cooking Class', ['Culinary School',
                                  'Online Cooking Platform', 'Community Center']],
    ['Exploring a Coral Reef', ['Tropical Ocean', 'Marine Biology Lab', 'Aquarium']],
    ['Debating a Philosophical Question', [
        'University Lecture Hall', 'Coffee Shop', 'Online Forum']],
    ['Performing Stand-up Comedy', ['Comedy Club', 'Open Mic Night', 'Online Stream']],
    ['Crafting Artisanal Cheese', ['Farmstead', 'Urban Food Market', 'Home Kitchen']],
    ['Designing a Video Game', ['Tech Startup Office',
                                'Home Office', 'Gaming Convention']],
    ['Participating in a Spelling Bee', [
        'School Auditorium', 'Community Hall', 'Online Meeting']],
    ['Hosting a Radio Show', ['Broadcast Studio', 'Home Studio', 'Public Event']],
    ['Solving a Complex Math Problem', [
        'University Math Department', 'Home Study', 'Public Library']],
    ['Restoring a Vintage Car', ['Garage Workshop', 'Automobile Museum', 'Car Show']],
    ['Creating a Perfume', ['Perfumery Lab', 'Botanical Garden', 'Market Stall']],
    ['Building a Treehouse', ['Backyard', 'Public Woodland', 'Adventure Park']],
    ['Organizing a Fashion Show', ['Designer Studio', 'City Venue', 'Online Broadcast']],
    ['Conducting a Spacewalk', ['Space Station',
                                'Training Facility', 'Simulation Room']],
    ['Investigating a Historical Mystery', [
        'Archive Room', 'Old Mansion', 'Historical Society']],
    ['Brewing Craft Beer', ['Microbrewery', 'Home Garage', 'Brewing Festival']],
    ['Training for a Marathon', ['City Streets', 'Mountain Trail', 'Sports Complex']],
    ['Developing a Mobile App', ['Tech Incubator', 'College Dorm', 'Home Office']],
    ['Cultivating a Rare Plant', ['Botanical Garden',
                                  'Research Greenhouse', 'Home Conservatory']],
    ['Navigating a Sailboat', ['Open Sea', 'Coastal Bay', 'Sailing School']],
    ['Organizing a Community Event', ['Local Park',
                                      'Community Center', 'Online Platform']],
    ['Painting a Mural', ['City Wall', 'Art School', 'Children’s Hospital']],
    ['Practicing Magic Tricks', ['Magic Shop', 'Home Office', 'Street Performance']],
    ['Studying Rare Birds', ['Wildlife Reserve', 'Mountain Observatory', 'Urban Park']],
    ['Hosting a Podcast', ['Recording Studio', 'Home Office', 'Live at an Event']],
    ['Climbing a Mountain', ['Rocky Peak',
                             'Indoor Climbing Gym', 'Virtual Reality Environment']],
    ['Curating an Art Exhibition', ['Art Gallery',
                                    'Online Gallery', 'Community Center']],
    ['Performing in a Circus', ['Big Top Tent', 'City Square', 'Theme Park']],
    ['Launching a Startup Company', [
        'Co-working Space', 'Home Garage', 'Business Incubator']],
    ['Exploring an Abandoned City', [
        'Ghost Town', 'Urban Ruins', 'Virtual Simulation']],
    ['Leading a Yoga Retreat', ['Beach Resort', 'Mountain Cabin', 'City Studio']],
    ['Solving an Escape Room', ['Themed Escape Room',
                                'Online Challenge', 'Team Building Event']],
    ['Racing in a Rally', ['Desert Track', 'Forest Path', 'Virtual Circuit']],
    ['Teaching a Language Online', ['Virtual Classroom',
                                    'Home Office', 'Language Learning App']],
    ['Participating in a Chess Tournament', [
        'Public Park', 'Online Platform', 'Community Hall']],
    ['Creating a Sustainable Garden', [
        'Rooftop Garden', 'Schoolyard', 'Community Plot']],
    ['Conducting an Orchestra', ['Concert Hall',
                                 'School Auditorium', 'Open-Air Festival']],
    ['Investigating a Cybercrime', ['Police Station',
                                    'Home Office', 'Cybersecurity Firm']],
    ['Filming a Documentary', ['Remote Village', 'Busy City', 'Natural Reserve']],
    ['Rebuilding a Historic Ship', [
        'Maritime Museum', 'Dockyard', 'Educational Workshop']]
]
